export const beverageVariants: ProductVariant[] = [
  {
    id: "succhi-di-frutta",
    name: "Succhi di frutta",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bibite-gassate",
    name: "Bibite gassate",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "te-freddo",
    name: "Tè freddo",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bevande-energetiche",
    name: "Bevande energetiche",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bevande-analcoliche",
    name: "Bevande analcoliche",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bevande-vegetali",
    name: "Bevande vegetali",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
];
