export const productCategories = [
  "Pasta",
  "Riso e cereali",
  "Sughi e condimenti",
  "Colazione",
  "Bevande",
  "Acqua",
  "Latticini",
  "Carne",
  "Pesce",
  "Frutta",
  "Verdura",
  "Surgelati",
  "Prodotti per la casa",
  "Igiene personale",
  "Auto",
  "Brico",
  "Giocattoli",
  "Cancelleria",
  "Teleria",
  "Intimo",
  "Banco freschi",
  "Pulizia per la casa",
  "Libri",
  "Animaleria",
  "Casalinghi",
  "Snack",
  "Dolciumi",
  "Profumeria",
  "Prima infanzia",
] as const;

export type ProductCategory = (typeof productCategories)[number];

export type ProductVariant = {
  id: string;
  name: string;
  category: ProductCategory;
  aisle: string;
  department: string;
  landmark: string;
};

export const pastaVariants: ProductVariant[] = [
  {
    id: "pasta-normale",
    name: "Pasta normale",
    category: "Pasta",
    aisle: "Corsia 7",
    department: "Pasta e prodotti secchi",
    landmark: "Riso e legumi",
  },
  {
    id: "pasta-integrale",
    name: "Pasta integrale",
    category: "Pasta",
    aisle: "Corsia 8",
    department: "Pasta e prodotti secchi",
    landmark: "Sughi e condimenti",
  },
  {
    id: "pasta-senza-glutine",
    name: "Pasta senza glutine",
    category: "Pasta",
    aisle: "Corsia 3",
    department: "Prodotti senza glutine",
    landmark: "Prodotti biologici",
  },
  {
    id: "pasta-all-uovo",
    name: "Pasta all'uovo",
    category: "Pasta",
    aisle: "Corsia 8",
    department: "Pasta e prodotti secchi",
    landmark: "Sughi e condimenti",
  },
  {
    id: "pasta-fresca",
    name: "Pasta fresca",
    category: "Pasta",
    aisle: "Banco frigo",
    department: "Banco frigo",
    landmark: "Latticini",
  },
];

export const riceAndCerealsVariants: ProductVariant[] = [
  {
    id: "riso",
    name: "Riso",
    category: "Riso e cereali",
    aisle: "Corsia 4",
    department: "Riso e cereali",
    landmark: "Riso e cereali",
  },
  {
    id: "riso-integrale",
    name: "Riso integrale",
    category: "Riso e cereali",
    aisle: "Corsia 4",
    department: "Riso e cereali",
    landmark: "Riso e cereali",
  },
  {
    id: "riso-basmati",
    name: "Riso basmati",
    category: "Riso e cereali",
    aisle: "Corsia 4",
    department: "Riso e cereali",
    landmark: "Riso e cereali",
  },
  {
    id: "cous-cous",
    name: "Cous cous",
    category: "Riso e cereali",
    aisle: "Corsia 4",
    department: "Riso e cereali",
    landmark: "Riso e cereali",
  },
  {
    id: "farro",
    name: "Farro",
    category: "Riso e cereali",
    aisle: "Corsia 4",
    department: "Riso e cereali",
    landmark: "Riso e cereali",
  },
  {
    id: "riso-pronto",
    name: "Riso Pronto",
    category: "Riso e cereali",
    aisle: "Corsia 4",
    department: "Riso e cereali",
    landmark: "Riso e cereali",
  },
];

export const saucesAndCondimentsVariants: ProductVariant[] = [
  {
    id: "passata-di-pomodoro",
    name: "Passata di pomodoro",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "polpa-di-pomodoro",
    name: "Polpa di pomodoro",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "sugo-pronto",
    name: "Sugo pronto",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "pesto",
    name: "Pesto",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "olio",
    name: "Olio",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "aceto",
    name: "Aceto",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "sale",
    name: "Sale",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "spezie",
    name: "Spezie",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
  {
    id: "dadi",
    name: "Dadi",
    category: "Sughi e condimenti",
    aisle: "Corsia 3",
    department: "Sughi e condimenti",
    landmark: "Sughi e condimenti",
  },
];

export const breakfastVariants: ProductVariant[] = [
  {
    id: "biscotti",
    name: "Biscotti",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "cereali",
    name: "Cereali",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "fette-biscottate",
    name: "Fette biscottate",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "marmellata",
    name: "Marmellata",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "miele",
    name: "Miele",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "creme-spalmabili",
    name: "Creme spalmabili",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "the",
    name: "Thè",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "caffe",
    name: "Caffè",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
  {
    id: "merendine",
    name: "Merendine",
    category: "Colazione",
    aisle: "Corsia 5",
    department: "Colazione",
    landmark: "Colazione",
  },
];

export const beverageVariants: ProductVariant[] = [
  {
    id: "succhi-di-frutta",
    name: "Succhi di frutta",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bibite-gassate",
    name: "Bibite gassate",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "te-freddo",
    name: "Tè freddo",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bevande-energetiche",
    name: "Bevande energetiche",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bevande-analcoliche",
    name: "Bevande analcoliche",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bevande-vegetali",
    name: "Bevande vegetali",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
  {
    id: "bevande-alcoliche",
    name: "Bevande alcoliche",
    category: "Bevande",
    aisle: "Corsia 2",
    department: "Bevande",
    landmark: "Bevande",
  },
];

export const waterVariants: ProductVariant[] = [
  {
    id: "acqua-naturale",
    name: "Acqua naturale",
    category: "Acqua",
    aisle: "Corsia 2",
    department: "Acqua",
    landmark: "Acqua",
  },
  {
    id: "acqua-frizzante",
    name: "Acqua frizzante",
    category: "Acqua",
    aisle: "Corsia 2",
    department: "Acqua",
    landmark: "Acqua",
  },
  {
    id: "acqua-leggermente-frizzante",
    name: "Acqua leggermente frizzante",
    category: "Acqua",
    aisle: "Corsia 2",
    department: "Acqua",
    landmark: "Acqua",
  },
  {
    id: "acqua-aromatizzata",
    name: "Acqua aromatizzata",
    category: "Acqua",
    aisle: "Corsia 2",
    department: "Acqua",
    landmark: "Acqua",
  },
];

export const dairyVariants: ProductVariant[] = [
  {
    id: "latte",
    name: "Latte",
    category: "Latticini",
    aisle: "Banco frigo",
    department: "Banco frigo",
    landmark: "Latticini",
  },
  {
    id: "yogurt",
    name: "Yogurt",
    category: "Latticini",
    aisle: "Banco frigo",
    department: "Banco frigo",
    landmark: "Latticini",
  },
  {
    id: "burro",
    name: "Burro",
    category: "Latticini",
    aisle: "Banco frigo",
    department: "Banco frigo",
    landmark: "Latticini",
  },
  {
    id: "formaggi",
    name: "Formaggi",
    category: "Latticini",
    aisle: "Banco frigo",
    department: "Banco frigo",
    landmark: "Latticini",
  },
  {
    id: "panna",
    name: "Panna",
    category: "Latticini",
    aisle: "Banco frigo",
    department: "Banco frigo",
    landmark: "Latticini",
  },
  {
    id: "ricotta",
    name: "Ricotta",
    category: "Latticini",
    aisle: "Banco frigo",
    department: "Banco frigo",
    landmark: "Latticini",
  },
];

export const meatVariants: ProductVariant[] = [
  {
    id: "pollo",
    name: "Pollo",
    category: "Carne",
    aisle: "Macelleria",
    department: "Macelleria",
    landmark: "Macelleria",
  },
  {
    id: "manzo",
    name: "Manzo",
    category: "Carne",
    aisle: "Macelleria",
    department: "Macelleria",
    landmark: "Macelleria",
  },
  {
    id: "maiale",
    name: "Maiale",
    category: "Carne",
    aisle: "Macelleria",
    department: "Macelleria",
    landmark: "Macelleria",
  },
  {
    id: "tacchino",
    name: "Tacchino",
    category: "Carne",
    aisle: "Macelleria",
    department: "Macelleria",
    landmark: "Macelleria",
  },
  {
    id: "hamburger",
    name: "Hamburger",
    category: "Carne",
    aisle: "Macelleria",
    department: "Macelleria",
    landmark: "Macelleria",
  },
  {
    id: "carne-macinata",
    name: "Carne macinata",
    category: "Carne",
    aisle: "Macelleria",
    department: "Macelleria",
    landmark: "Macelleria",
  },
];

export const fishVariants: ProductVariant[] = [
  {
    id: "pesce-fresco",
    name: "Pesce fresco",
    category: "Pesce",
    aisle: "Pescheria",
    department: "Pescheria",
    landmark: "Pescheria",
  },
  {
    id: "pesce-surgelato",
    name: "Pesce surgelato",
    category: "Pesce",
    aisle: "Pescheria",
    department: "Pescheria",
    landmark: "Pescheria",
  },
  {
    id: "salmone",
    name: "Salmone",
    category: "Pesce",
    aisle: "Pescheria",
    department: "Pescheria",
    landmark: "Pescheria",
  },
  {
    id: "tonno",
    name: "Tonno",
    category: "Pesce",
    aisle: "Pescheria",
    department: "Pescheria",
    landmark: "Pescheria",
  },
  {
    id: "merluzzo",
    name: "Merluzzo",
    category: "Pesce",
    aisle: "Pescheria",
    department: "Pescheria",
    landmark: "Pescheria",
  },
  {
    id: "molluschi-e-crostacei",
    name: "Molluschi e crostacei",
    category: "Pesce",
    aisle: "Pescheria",
    department: "Pescheria",
    landmark: "Pescheria",
  },
];

export const fruitVariants: ProductVariant[] = [
  {
    id: "mele",
    name: "Mele",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "banane",
    name: "Banane",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "arance",
    name: "Arance",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "pere",
    name: "Pere",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "uva",
    name: "Uva",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "frutta-esotica",
    name: "Frutta esotica",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "noci",
    name: "Noci",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "mandorle",
    name: "Mandorle",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "arachidi",
    name: "Arachidi",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "nocciole",
    name: "Nocciole",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "pistacchi",
    name: "Pistacchi",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "anacardi",
    name: "Anacardi",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "patate",
    name: "Patate",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "pomodori",
    name: "Pomodori",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "zucchine",
    name: "Zucchine",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "carote",
    name: "Carote",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "insalata",
    name: "Insalata",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
  {
    id: "verdure-a-foglia",
    name: "Verdure a foglia",
    category: "Frutta",
    aisle: "Frutta",
    department: "Frutta",
    landmark: "Frutta",
  },
];

export const frozenVariants: ProductVariant[] = [
  {
    id: "verdure-surgelate",
    name: "Verdure surgelate",
    category: "Surgelati",
    aisle: "Surgelati",
    department: "Surgelati",
    landmark: "Surgelati",
  },
  {
    id: "patatine-surgelate",
    name: "Patatine surgelate",
    category: "Surgelati",
    aisle: "Surgelati",
    department: "Surgelati",
    landmark: "Surgelati",
  },
  {
    id: "pizza-surgelata",
    name: "Pizza surgelata",
    category: "Surgelati",
    aisle: "Surgelati",
    department: "Surgelati",
    landmark: "Surgelati",
  },
  {
    id: "gelati",
    name: "Gelati",
    category: "Surgelati",
    aisle: "Surgelati",
    department: "Surgelati",
    landmark: "Surgelati",
  },
  {
    id: "piatti-pronti-surgelati",
    name: "Piatti pronti surgelati",
    category: "Surgelati",
    aisle: "Surgelati",
    department: "Surgelati",
    landmark: "Surgelati",
  },
  {
    id: "pesce-surgelato",
    name: "Pesce surgelato",
    category: "Surgelati",
    aisle: "Surgelati",
    department: "Surgelati",
    landmark: "Surgelati",
  },
];

export const homeProductsVariants: ProductVariant[] = [
  {
    id: "detersivo-piatti",
    name: "Detersivo per piatti",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "detersivo-lavatrice",
    name: "Detersivo per lavatrice",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "detersivo-pavimenti",
    name: "Detersivo per pavimenti",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "ammorbidente",
    name: "Ammorbidente",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "sgrassatore",
    name: "Sgrassatore",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "detergente-multiuso",
    name: "Detergente multiuso",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "guanti",
    name: "Guanti",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "scope",
    name: "Scope",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "mop",
    name: "Mop",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "assi-da-stiro",
    name: "Assi da stiro",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "stendini",
    name: "Stendini",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "bacinelle",
    name: "Bacinelle",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "contenitori-con-coperchio",
    name: "Contenitori con coperchio",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "insetticidi",
    name: "Insetticidi",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "profumatori",
    name: "Profumatori",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "candele",
    name: "Candele",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "secchi-immondizia",
    name: "Secchi per immondizia",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "prodotti-armadio",
    name: "Prodotti per l'armadio",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
  {
    id: "buste-immondizia",
    name: "Buste per immondizia",
    category: "Prodotti per la casa",
    aisle: "Prodotti per la casa",
    department: "Prodotti per la casa",
    landmark: "Prodotti per la casa",
  },
];

export const personalCareVariants: ProductVariant[] = [
  {
    id: "shampoo",
    name: "Shampoo",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "bagnoschiuma",
    name: "Bagnoschiuma",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "sapone",
    name: "Sapone",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "dentifricio",
    name: "Dentifricio",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "deodorante",
    name: "Deodorante",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "carta-igienica",
    name: "Carta igienica",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "spazzolini",
    name: "Spazzolini",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "tinte-capelli",
    name: "Tinte per capelli",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "creme-corpo",
    name: "Creme corpo",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "solette",
    name: "Solette",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "prodotti-medicamentali",
    name: "Prodotti medicamentali",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "prodotti-barba",
    name: "Prodotti per barba",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
  {
    id: "accessori",
    name: "Accessori",
    category: "Igiene personale",
    aisle: "Igiene personale",
    department: "Igiene personale",
    landmark: "Igiene personale",
  },
];

export const autoVariants: ProductVariant[] = [
  {
    id: "accessori-auto",
    name: "Accessori auto",
    category: "Auto",
    aisle: "Auto",
    department: "Auto",
    landmark: "Auto",
  },
  {
    id: "prodotti-pulizia-auto",
    name: "Prodotti per la pulizia auto",
    category: "Auto",
    aisle: "Auto",
    department: "Auto",
    landmark: "Auto",
  },
  {
    id: "profumatori-auto",
    name: "Profumatori auto",
    category: "Auto",
    aisle: "Auto",
    department: "Auto",
    landmark: "Auto",
  },
  {
    id: "lampadine-auto",
    name: "Lampadine auto",
    category: "Auto",
    aisle: "Auto",
    department: "Auto",
    landmark: "Auto",
  },
  {
    id: "tappetini-auto",
    name: "Tappetini auto",
    category: "Auto",
    aisle: "Auto",
    department: "Auto",
    landmark: "Auto",
  },
  {
    id: "oli-e-liquidi-auto",
    name: "Oli e liquidi auto",
    category: "Auto",
    aisle: "Auto",
    department: "Auto",
    landmark: "Auto",
  },
];

export const diyVariants: ProductVariant[] = [
  {
    id: "utensili-manuali",
    name: "Utensili manuali",
    category: "Brico",
    aisle: "Brico",
    department: "Brico",
    landmark: "Brico",
  },
  {
    id: "viti-e-bulloni",
    name: "Viti e bulloni",
    category: "Brico",
    aisle: "Brico",
    department: "Brico",
    landmark: "Brico",
  },
  {
    id: "collanti",
    name: "Collanti",
    category: "Brico",
    aisle: "Brico",
    department: "Brico",
    landmark: "Brico",
  },
  {
    id: "nastri-adesivi",
    name: "Nastri adesivi",
    category: "Brico",
    aisle: "Brico",
    department: "Brico",
    landmark: "Brico",
  },
  {
    id: "ferramenta",
    name: "Ferramenta",
    category: "Brico",
    aisle: "Brico",
    department: "Brico",
    landmark: "Brico",
  },
  {
    id: "materiale-elettrico",
    name: "Materiale elettrico",
    category: "Brico",
    aisle: "Brico",
    department: "Brico",
    landmark: "Brico",
  },
];

export const toysVariants: ProductVariant[] = [
  {
    id: "giochi-da-tavolo",
    name: "Giochi da tavolo",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "puzzle",
    name: "Puzzle",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "bambole",
    name: "Bambole",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "costruzioni",
    name: "Costruzioni",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "macchinine",
    name: "Macchinine",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "peluche",
    name: "Peluche",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "giochi-prima-infanzia",
    name: "Giochi prima infanzia",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "giochi-didattici",
    name: "Giochi didattici",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "lego",
    name: "LEGO",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "playmobil",
    name: "Playmobil",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
  {
    id: "pasta-modellabile",
    name: "Pasta modellabile",
    category: "Giocattoli",
    aisle: "Giocattoli",
    department: "Giocattoli",
    landmark: "Giocattoli",
  },
];

export const stationeryVariants: ProductVariant[] = [
  {
    id: "quaderni",
    name: "Quaderni",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
  {
    id: "penne",
    name: "Penne",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
  {
    id: "matite",
    name: "Matite",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
  {
    id: "gomme",
    name: "Gomme",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
  {
    id: "astucci",
    name: "Astucci",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
  {
    id: "materiale-da-disegno",
    name: "Materiale da disegno",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
  {
    id: "cartelle",
    name: "Cartelle",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
  {
    id: "buste-da-lettera",
    name: "Buste da lettera",
    category: "Cancelleria",
    aisle: "Cancelleria",
    department: "Cancelleria",
    landmark: "Cancelleria",
  },
];

export const teleriaVariants: ProductVariant[] = [
  {
    id: "lenzuola",
    name: "Lenzuola",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
  {
    id: "copriletto",
    name: "Copriletto",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
  {
    id: "coperte",
    name: "Coperte",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
  {
    id: "asciugamani",
    name: "Asciugamani",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
  {
    id: "tovaglie",
    name: "Tovaglie",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
  {
    id: "tende",
    name: "Tende",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
  {
    id: "presine",
    name: "Presine",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
  {
    id: "strofinacci",
    name: "Strofinacci",
    category: "Teleria",
    aisle: "Teleria",
    department: "Teleria",
    landmark: "Teleria",
  },
];

